Handle edge case of a Youwee update moving from HKLM to HKCU

diff --git a/scripts/events/download-url b/scripts/events/download-url
--- a/scripts/events/download-url
+++ b/scripts/events/download-url
@@ -28,15 +28,28 @@
 set -o errexit -o nounset
 
 locate_youwee_in_wsl() {
-    # FIXME slow to run PowerShell, and slow to use `Get-Package`
-    #   - registry queries are brittle and hardcode too much?
-    #   - querying `shell:AppsFolder` breaks if the app shortcut is removed
-    powershell.exe -NonInteractive '(Get-Package -Name Youwee).Source' \
+    # Check Package Management first, and only then resort to a registry query.
+    # https://learn.microsoft.com/powershell/module/packagemanagement/get-package
+    #
+    # If Youwee is initially installed via an MSI installer and later updated,
+    # then it will be relocated/re-installed to the user's `%APPDATA%`,
+    # which `Get-Package` won't be able to locate.
+    { {
+        powershell.exe -NonInteractive '(Get-Package -Name Youwee).Source' \
         | tr -d '\r' \
-        | xargs -d '\n' wslpath
+        | grep .
+    } \
+    || {
+        reg.exe query 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Youwee' \
+        | grep InstallLocation \
+        | tr -d '\r' \
+        | grep -oP '[^\s"]*\\[^"]+'
+    } } \
+    | xargs -d '\n' wslpath
 }
 
 run_youwee_via_wsl() {
+    # FIXME failing to run `ffmpeg` under Windows when Dropbox is running?
     "$(locate_youwee_in_wsl)/youwee.exe" "$@"
 }
 
@@ -75,6 +88,11 @@ download_via_media_downloader() {
 
 # TODO option for rolling downloads? eg. only the last `n` NRK news episodes
 for url; do
+    if ! in_wsl; then
+        # FIXME not currently working from within WSL
+        notify-send 'Enclosure URL' "$url"
+    fi
+
     # FIXME ensure apps are always spawn in the background?
     download_via_youwee_cli "$url" 720
 
